
services:
  - type: web
    name: attendance-monitoring
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
    plan: free
